version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    restart: unless-stopped
    ports:
      - "8096:8096"
      - "8920:8920"
      - "7359:7359/udp"
      - "1900:1900/udp"
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./media:/media:ro
      - ./jellyfin/transcodes:/transcodes
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.178.99:8096
      - TZ=Europe/Berlin
    networks:
      - media-network
    devices:
      - /dev/dri:/dev/dri # For hardware acceleration (if available)

networks:
  media-network:
    driver: bridge

volumes:
  media:
    driver: local